info:
  name: get specefic billing settings
  type: http
  seq: 7

http:
  method: GET
  url: "{{clientUrl}}/api/v1/billing-reminder/billing/settings/:quotationId?type=quotation"
  params:
    - name: type
      value: quotation
      type: query
    - name: projection
      value: option.accountSetting.accountsToUse
      type: query
      disabled: true
    - name: quotationId
      value: 6a216d54c729a79c7ac6f00e
      type: path
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
