info:
  name: Set Individual billing settings
  type: http
  seq: 6

http:
  method: PUT
  url: "{{clientUrl}}/api/v1/billing-reminder/billing/settings/:quotationId?type=quotation&replace=true"
  params:
    - name: type
      value: quotation
      type: query
    - name: replace
      value: "true"
      type: query
    - name: quotationId
      value: 6a216d54c729a79c7ac6f00e
      type: path
  body:
    type: json
    data: |-
      {
          // "accountConfigType":false,
          // "options": {
          //     "accountSetting": {
          //         "stopSendingOnReply": true,
          //         "sendEmailAsTextOnly": false,
          //         "sendFirstEmailAsTextOnly": true,
          //         "dailyLimit": 555,
          //         "accountsToUse": [
          //             "priti@pentagoat.com"
          //         ]
          //     },
          //     "ccBcc": {
          //         "ccRecipients": "priti@pentagoat.com",
          //         "bccRecipients": "priti@pentagoat.com"
          //     }
          // }
          // "schedule": [
          //     {
          //         "scheduleName": "Morning Outreachsahehe pooja",
          //         "isActive": true,
          //         "startDate": "2025-11-01T00:00:00.000Z",
          //         "endDate": "2026-12-31T23:59:59.000Z",
          //         "timeFrom": "01:00",
          //         "timeTo": "23:30",
          //         "timeZone": "Asia/Kolkata",
          //         "weekDays": [
          //             "monday",
          //             "tuesday",
          //             "wednesday",
          //             "thursday",
          //             "friday",
          //             "saturday"
          //         ]
          //     }
          // ]
          // "sequence": [
          //     {
          //         "stepOrder": 1,
          //         "stepName": "first proforma1",
          //         "nextMsgInDays":0.0001,
          //         "emails": {
          //             "subject": "Welcome to the Family!",
          //             "body": "We’re thrilled {{personName}} to have you. Let’s take a quick tour of what you can do here.",
          //             "isActive": true,
          //             "placeholders": [
          //                 {
          //                     "key": "personName",
          //                     "description": "hehe",
          //                     "sampleValue": "vindefault"
          //                 }
          //             ]
          //         }
          //     },
          //     {
          //         "stepOrder": 2,
          //         "stepName": "second",
          //         "nextMsgInDays": 0.0001,
          //         "emails": {
          //             // "subject": "Welcome to dashboard",
          //             "body": "Here’s how to get started using your dashboard efficiently.",
          //             "isActive": true
          //         }
          //     },
          //     {
          //         "stepOrder": 4,
          //         "stepName": "forth",
          //         "emails": {
          //             // "subject": "Welcome to dashboard",
          //             "body": "Here’s how to get started using your dashboard efficiently.",
          //             "isActive": true
          //         }
          //     },
          //     {
          //         "stepOrder": 3,
          //         "stepName": "third",
          //         "nextMsgInDays": 0.0001,
          //         "emails": {
          //             // "subject": "Welcome to dashboard",
          //             "body": "Here’s how to get started using your dashboard efficiently.",
          //             "isActive": true
          //         }
          //     }
          // ]
      //    , 
         "launch": false
      // "relaunch":true
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
