info:
  name: Update/Create Quotation Settings
  type: http
  seq: 2

http:
  method: PATCH
  url: "{{clientUrl}}/api/v1/quotation/settings"
  body:
    type: multipart-form
    data:
      - name: footerNote
        type: text
        value: '{"terms":"","notes":""}'
        disabled: true
      - name: signature
        type: file
        value:
          - C:\Users\admin\Pictures\signature.png
        disabled: true
      - name: logo
        type: file
        value:
          - C:\Users\admin\Pictures\—Pngtree—media company logo design vector_6866366.png
      - name: signature
        type: text
        value: |-
          {
                          "uuid": "2d8a404c-d59e-427c-aea5-cde415786a26",
                          "title": "172.png-quotationSignature",
                          "data": "https://pipingproject.s3.ap-south-1.amazonaws.com/piplineBillingDevelopment/172_1761546101550.png",
                          "_id": "68ff0f75020fd4f6862556a1"
                      }
        disabled: true
      - name: logo
        type: text
        value: |2-
           {
                          "uuid": "8470dee9-d215-4d27-bd87-0426274f4fc8",
                          "title": "004.png-quotationLogo",
                          "data": "https://pipingproject.s3.ap-south-1.amazonaws.com/piplineBillingDevelopment/004_1772019889192.png",
                          "_id": "699ee0b96c3f4d6ee00fab09"
                      }
        disabled: true
      - name: deleteFiles
        type: text
        value: |-
          [{"logo": {
                          "uuid": "8470dee9-d215-4d27-bd87-0426274f4fc8",
                          "title": "004.png-quotationLogo",
                          "data": "https://pipingproject.s3.ap-south-1.amazonaws.com/piplineBillingDevelopment/004_1772019889192.png",
                          "_id": "699ee0b96c3f4d6ee00fab09"
                      }}]
        disabled: true
      - name: taxSlabs
        type: text
        value: |
          [{"name":"ll","value":0,"default":false,"_id":"6996b6612e525ef004731139"},{"name":"geeg","value":21}]
        disabled: true
      - name: companyName
        type: text
        value: QUOTATION
        disabled: true
      - name: ownerName
        type: text
        value: vin22
        disabled: true
      - name: email
        type: text
        value: vin@gmail.conm
        disabled: true
      - name: countryCode
        type: text
        value: "91"
        disabled: true
      - name: number
        type: text
        value: "9136285805"
        disabled: true
      - name: city
        type: text
        value: mumbai
        disabled: true
      - name: state
        type: text
        value: maharashtra
        disabled: true
      - name: postal_code
        type: text
        value: "400080"
        disabled: true
      - name: country
        type: text
        value: India
        disabled: true
      - name: address_type
        type: text
        value: Office
        disabled: true
      - name: address
        type: text
        value: my_address
        disabled: true
      - name: region
        type: text
        value: '{"isoCode":"IN","name":"India","dialCode":"+91"}'
        disabled: true
  auth:
    type: bearer
    token: "{{token}}"

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
