name: Dev
color: "#346AB2"
variables:
  - name: clientUrl
    value: http://localhost:9000
  - name: scriptUrl
    value: http://localhost:4060
  - name: userUrl
    value: http://localhost:4000
  - name: webUrl
    value: http://localhost:5050
  - name: url
    value: http://localhost:5000
